# Generated by Django 6.0.1 on 2026-03-06 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_sender_business_name_alter_sender_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rider',
            name='vehicle_type',
            field=models.CharField(choices=[('bike', 'Bike'), ('car', 'Car'), ('van', 'Van')], default='bike', max_length=20),
        ),
    ]
